### ISSUE TITLE
SequenceServer::DATABASE_DIR_NOT_SET: Database dir not set.

### ISSUE THREAD

**Issue by mictadlo** [homonecloco/expvip-web#42]
Hi,
I the following Dockerfile:
```
FROM debian:stretch-backports
RUN apt-get update  && apt-get install -y --no-install-recommends \
        build-essential \
        ruby ruby-dev \
        curl wget \
        gnupg \
        git \
        ncbi-blast+ \
        libmariadbclient-dev \
        libsqlite3-dev \
        zlib1g-dev && \
        apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
        apt-get update  && apt-get install -y --no-install-recommends \
        nodejs npm && \
        apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV EXPVIP_VERSION Release-2018-07-17

RUN wget -c https://github.com/homonecloco/expvip-web/archive/${EXPVIP_VERSION}.tar.gz  && \
    tar xfvz ${EXPVIP_VERSION}.tar.gz && \
    cd expvip-web-${EXPVIP_VERSION} && \
    gem install bundler && \
    bundle install && \
    sed -i.bak "s|localhost|expvip_db|" config/database.yml && \
    rake db:migrate
```

and here is the `docker-compose.yml` file:

```
expvip:
    build: .
    restart: always
    ports:
        - "80:80"
    links:
        - expvip_db
        - exvip_mongo
    volumes:
        - ./data/:/data

expvip_db:
  image: mariadb
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=expvip
    - MYSQL_USER=expvipUSR
    - MYSQL_PASSWORD=expvipPWD
  ports:
    - "3306:3306"
  volumes:
    - ./mysql/:/docker-entrypoint-initdb.d

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  links:
    - expvip_db
  ports:
    - 8183:80
  environment:
    PMA_USER: root
    PMA_PASSWORD: admin
    PMA_ARBITRARY: 1

exvip_mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/:/mongo
```

When I ran `docker-compose up` I got this error:

```
rake aborted!
SequenceServer::DATABASE_DIR_NOT_SET: Database dir not set.
/var/lib/gems/2.3.0/bundler/gems/sequenceserver-68e2054febe7/lib/sequenceserver.rb:123:in `init_database'
/var/lib/gems/2.3.0/bundler/gems/sequenceserver-68e2054febe7/lib/sequenceserver.rb:40:in `init'
/expvip-web-Release-2018-07-17/config/routes.rb:45:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:436:in `instance_exec'
/var/lib/gems/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:436:in `eval_block'
/var/lib/gems/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:418:in `draw'
/expvip-web-Release-2018-07-17/config/routes.rb:3:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `load'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `load'
/var/lib/gems/2.3.0/gems/railties-5.1.6/lib/rails/application/routes_reloader.rb:55:in `block in load_paths'
/var/lib/gems/2.3.0/gems/railties-5.1.6/lib/rails/application/routes_reloader.rb:55:in `each'
/var/lib/gems/2.3.0/gems/railties-5.1.6/lib/rails/application/routes_reloader.rb:55:in `load_paths'
/var/lib/gems/2.3.0/gems/railties-5.1.6/lib/rails/application/routes_reloader.rb:18:in `reload!'
/var/lib/gems/2.3.0/gems/railties-5.1.6/lib/rails/application/routes_reloader.rb:41:in `block in updater'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/file_update_checker.rb:81:in `execute'
/var/lib/gems/2.3.0/gems/railties-5.1.6/lib/rails/application/routes_reloader.rb:42:in `updater'
/var/lib/gems/2.3.0/gems/railties-5.1.6/lib/rails/application/routes_reloader.rb:31:in `execute_if_updated'
/var/lib/gems/2.3.0/gems/railties-5.1.6/lib/rails/application/finisher.rb:128:in `block in <module:Finisher>'
/var/lib/gems/2.3.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.3.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.3.0/gems/railties-5.1.6/lib/rails/initializable.rb:59:in `block in run_initializers'
/var/lib/gems/2.3.0/gems/railties-5.1.6/lib/rails/initializable.rb:58:in `run_initializers'
/var/lib/gems/2.3.0/gems/railties-5.1.6/lib/rails/application.rb:353:in `initialize!'
/expvip-web-Release-2018-07-17/config/environment.rb:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/var/lib/gems/2.3.0/gems/railties-5.1.6/lib/rails/application.rb:329:in `require_environment!'
/var/lib/gems/2.3.0/gems/railties-5.1.6/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/var/lib/gems/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

What did I miss?

Thank you in advance,

Michal
